export const ELEMENTS = {
    registerButtonNow: "[data-test=register]",
    registerButton: "[data-test=btnRegister]",
    emailField: "input[data-test=email]",
    fullNameField: "input[data-test=fullName]",
    userNameField: "input[data-test=registerUserName]",
    passwordField: "input[data-test=registerPassword]",
    availableUserMessage: "User available",
    notAvailableUserMessage: "Username already taken",
    miniumPasswordLength: "Mininum length is 8",
    emailRequiredMessage: "Email is required!",
    nameRequiredMessage: "Full name is required!",
    userNameRequiredMessage: "User name is required!",
    passwordRequiredMessage: "Password is required!",
}